version: '3.7'
services:
#  acme-order:
#    container_name: acme-order
#    image: acme-order
#    restart: always
#    depends_on:
#      - "mongodb"
#    build: .
#    ports:
#      - "80:80"
#    links:
#      - mongodb 
  mongodb:
    container_name: acme-order-mongodb
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: OrdersDb
    ports:
      - "27017:27017"